// Copyright 2025 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default {
  cssContent: `/*
 * Copyright 2024 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  display: flex;
  align-items: center;
  max-width: 100%;
  height: 20px;
}

devtools-select-menu {
  min-width: 160px;
  max-width: 100%;
  height: 20px;
}

/*# sourceURL=${import.meta.resolve('./networkThrottlingSelector.css')} */
`
};