// Copyright 2025 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default {
  cssContent: `/*
 * Copyright (c) 2019 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

 devtools-data-grid {
  flex: auto;
}

.cookies-table devtools-icon {
  margin-right: 4px;
}
/*# sourceURL=${import.meta.resolve('./cookiesTable.css')} */
`
};