// Copyright 2023 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright (c) 2022 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.reset-budget-button {
  width: 16px;
  height: 16px;
  background: transparent;
  overflow: hidden;
  border: none;
  padding: 0;
  outline: none;
  margin-left: 5px;
  margin-top: -4px;
  vertical-align: middle;
}

.reset-budget-button:hover devtools-icon {
  --icon-color: var(--color-text-primary);
}

.reset-budget-button:focus devtools-icon {
  --icon-color: var(--color-text-secondary);
}

.icon-basic {
  width: 12px;
  height: 14px;
}

/*# sourceURL=sharedStorageMetadataViewResetBudgetButton.css */
`);
export default styles;
