import * as UI from '../../ui/legacy/legacy.js';
import type { SearchScope } from './SearchConfig.js';
export declare class SearchView extends UI.Widget.VBox {
    private focusOnShow;
    private isIndexing;
    private searchId;
    private searchMatchesCount;
    private searchResultsCount;
    private nonEmptySearchResultsCount;
    private searchingView;
    private notFoundView;
    private searchConfig;
    private pendingSearchConfig;
    private searchResultsPane;
    private progressIndicator;
    private visiblePane;
    private readonly searchPanelElement;
    private readonly searchResultsElement;
    private search;
    private matchCaseButton;
    private readonly regexButton;
    private searchMessageElement;
    private readonly searchProgressPlaceholderElement;
    private searchResultsMessageElement;
    private readonly advancedSearchConfig;
    private searchScope;
    constructor(settingKey: string);
    private static appendToolbarToggle;
    private buildSearchConfig;
    toggle(queryCandidate: string, searchImmediately?: boolean): Promise<void>;
    createScope(): SearchScope;
    private initScope;
    wasShown(): void;
    private onIndexingFinished;
    private startIndexing;
    private onSearchInputClear;
    private onSearchResult;
    private onSearchFinished;
    private startSearch;
    private innerStartSearch;
    private resetSearch;
    private clearSearchMessage;
    private stopSearch;
    private searchStarted;
    private indexingFinished;
    private updateSearchResultsMessage;
    private showPane;
    private resetCounters;
    private nothingFound;
    private addSearchResult;
    private searchFinished;
    focus(): void;
    willHide(): void;
    private onKeyDown;
    private onKeyDownOnPanel;
    private save;
    private load;
    private onAction;
}
