// Copyright 2023 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2023 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.toolbar {
  display: flex;
  justify-content: space-between;
  padding-left: 5px;
  padding-right: 10px;
  padding-top: 1px;
  height: 27px;
  background-color: var(--color-background);
  position: absolute;
  bottom: 0;
  width: 100%;
  border-top: 1px solid var(--color-button-secondary-border);
}

/*# sourceURL=toolbar.css */
`);
export default styles;
