export const KNOWN_EVENTS = new Map([
    /* Task/Other */
    ["Program" /* KnownEventName.Program */, { category: "Other" /* EventCategory.Other */, label: 'Other' }],
    ["RunTask" /* KnownEventName.RunTask */, { category: "Other" /* EventCategory.Other */, label: 'Run Task' }],
    ["AsyncTask" /* KnownEventName.AsyncTask */, { category: "Other" /* EventCategory.Other */, label: 'Async Task' }],
    /* Load */
    ["XHRLoad" /* KnownEventName.XHRLoad */, { category: "Load" /* EventCategory.Load */, label: 'Load' }],
    ["XHRReadyStateChange" /* KnownEventName.XHRReadyStateChange */, { category: "Load" /* EventCategory.Load */, label: 'ReadyStateChange' }],
    /* Parse */
    ["ParseHTML" /* KnownEventName.ParseHTML */, { category: "Parse" /* EventCategory.Parse */, label: 'Parse HTML' }],
    ["ParseAuthorStyleSheet" /* KnownEventName.ParseCSS */, { category: "Parse" /* EventCategory.Parse */, label: 'Parse StyleSheet' }],
    /* V8 */
    ["V8.CompileScript" /* KnownEventName.CompileScript */, { category: "V8" /* EventCategory.V8 */, label: 'Compile Script' }],
    ["V8.CompileCode" /* KnownEventName.CompileCode */, { category: "V8" /* EventCategory.V8 */, label: 'Compile Code' }],
    ["V8.CompileModule" /* KnownEventName.CompileModule */, { category: "V8" /* EventCategory.V8 */, label: 'Compile Module' }],
    ["V8.OptimizeCode" /* KnownEventName.Optimize */, { category: "V8" /* EventCategory.V8 */, label: 'Optimize' }],
    ["v8.wasm.streamFromResponseCallback" /* KnownEventName.WasmStreamFromResponseCallback */, { category: "Js" /* EventCategory.Js */, label: 'Streaming Wasm Response' }],
    ["v8.wasm.compiledModule" /* KnownEventName.WasmCompiledModule */, { category: "Js" /* EventCategory.Js */, label: 'Compiled Wasm Module' }],
    ["v8.wasm.cachedModule" /* KnownEventName.WasmCachedModule */, { category: "Js" /* EventCategory.Js */, label: 'Cached Wasm Module' }],
    ["v8.wasm.moduleCacheHit" /* KnownEventName.WasmModuleCacheHit */, { category: "Js" /* EventCategory.Js */, label: 'Wasm Module Cache Hit' }],
    ["v8.wasm.moduleCacheInvalid" /* KnownEventName.WasmModuleCacheInvalid */, { category: "Js" /* EventCategory.Js */, label: 'Wasm Module Cache Invalid' }],
    /* Js */
    ["RunMicrotasks" /* KnownEventName.RunMicrotasks */, { category: "Js" /* EventCategory.Js */, label: 'Run Microtasks' }],
    ["EvaluateScript" /* KnownEventName.EvaluateScript */, { category: "Js" /* EventCategory.Js */, label: 'Evaluate Script' }],
    ["FunctionCall" /* KnownEventName.FunctionCall */, { category: "Js" /* EventCategory.Js */, label: 'Function Call' }],
    ["EventDispatch" /* KnownEventName.EventDispatch */, { category: "Js" /* EventCategory.Js */, label: 'Event' }],
    ["RequestMainThreadFrame" /* KnownEventName.RequestMainThreadFrame */, { category: "Js" /* EventCategory.Js */, label: 'Request Main Thread Frame' }],
    ["RequestAnimationFrame" /* KnownEventName.RequestAnimationFrame */, { category: "Js" /* EventCategory.Js */, label: 'Request Animation Frame' }],
    ["CancelAnimationFrame" /* KnownEventName.CancelAnimationFrame */, { category: "Js" /* EventCategory.Js */, label: 'Cancel Animation Frame' }],
    ["FireAnimationFrame" /* KnownEventName.FireAnimationFrame */, { category: "Js" /* EventCategory.Js */, label: 'Animation Frame' }],
    ["RequestIdleCallback" /* KnownEventName.RequestIdleCallback */, { category: "Js" /* EventCategory.Js */, label: 'Request Idle Callback' }],
    ["CancelIdleCallback" /* KnownEventName.CancelIdleCallback */, { category: "Js" /* EventCategory.Js */, label: 'Cancel Idle Callback' }],
    ["FireIdleCallback" /* KnownEventName.FireIdleCallback */, { category: "Js" /* EventCategory.Js */, label: 'Idle Callback' }],
    ["TimerInstall" /* KnownEventName.TimerInstall */, { category: "Js" /* EventCategory.Js */, label: 'Timer Installed' }],
    ["TimerRemove" /* KnownEventName.TimerRemove */, { category: "Js" /* EventCategory.Js */, label: 'Timer Removed' }],
    ["TimerFire" /* KnownEventName.TimerFire */, { category: "Js" /* EventCategory.Js */, label: 'Timer Fired' }],
    ["WebSocketCreate" /* KnownEventName.WebSocketCreate */, { category: "Js" /* EventCategory.Js */, label: 'Create WebSocket' }],
    ["WebSocketSendHandshakeRequest" /* KnownEventName.WebSocketSendHandshake */, { category: "Js" /* EventCategory.Js */, label: 'Send WebSocket Handshake' }],
    ["WebSocketReceiveHandshakeResponse" /* KnownEventName.WebSocketReceiveHandshake */, { category: "Js" /* EventCategory.Js */, label: 'Receive WebSocket Handshake' }],
    ["WebSocketDestroy" /* KnownEventName.WebSocketDestroy */, { category: "Js" /* EventCategory.Js */, label: 'Destroy WebSocket' }],
    ["DoEncrypt" /* KnownEventName.CryptoDoEncrypt */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Encrypt' }],
    ["DoEncryptReply" /* KnownEventName.CryptoDoEncryptReply */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Encrypt Reply' }],
    ["DoDecrypt" /* KnownEventName.CryptoDoDecrypt */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Decrypt' }],
    ["DoDecryptReply" /* KnownEventName.CryptoDoDecryptReply */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Decrypt Reply' }],
    ["DoDigest" /* KnownEventName.CryptoDoDigest */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Digest' }],
    ["DoDigestReply" /* KnownEventName.CryptoDoDigestReply */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Digest Reply' }],
    ["DoSign" /* KnownEventName.CryptoDoSign */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Sign' }],
    ["DoSignReply" /* KnownEventName.CryptoDoSignReply */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Sign Reply' }],
    ["DoVerify" /* KnownEventName.CryptoDoVerify */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Verify' }],
    ["DoVerifyReply" /* KnownEventName.CryptoDoVerifyReply */, { category: "Js" /* EventCategory.Js */, label: 'Crypto Verify Reply' }],
    /* Gc */
    ["GCEvent" /* KnownEventName.GC */, { category: "Gc" /* EventCategory.Gc */, label: 'GC' }],
    ["BlinkGC.AtomicPhase" /* KnownEventName.DOMGC */, { category: "Gc" /* EventCategory.Gc */, label: 'DOM GC' }],
    ["V8.GCIncrementalMarking" /* KnownEventName.IncrementalGCMarking */, { category: "Gc" /* EventCategory.Gc */, label: 'Incremental GC' }],
    ["MajorGC" /* KnownEventName.MajorGC */, { category: "Gc" /* EventCategory.Gc */, label: 'Major GC' }],
    ["MinorGC" /* KnownEventName.MinorGC */, { category: "Gc" /* EventCategory.Gc */, label: 'Minor GC' }],
    /* Layout (a.k.a "Rendering") */
    ["ScheduleStyleRecalculation" /* KnownEventName.ScheduleStyleRecalculation */, { category: "Layout" /* EventCategory.Layout */, label: 'Schedule Recalculate Style' }],
    ["RecalculateStyles" /* KnownEventName.RecalculateStyles */, { category: "Layout" /* EventCategory.Layout */, label: 'Recalculate Style' }],
    ["Layout" /* KnownEventName.Layout */, { category: "Layout" /* EventCategory.Layout */, label: 'Layout' }],
    ["UpdateLayoutTree" /* KnownEventName.UpdateLayoutTree */, { category: "Layout" /* EventCategory.Layout */, label: 'Recalculate Style' }],
    ["InvalidateLayout" /* KnownEventName.InvalidateLayout */, { category: "Layout" /* EventCategory.Layout */, label: 'Invalidate Layout' }],
    ["LayoutInvalidationTracking" /* KnownEventName.LayoutInvalidationTracking */, { category: "Layout" /* EventCategory.Layout */, label: 'Layout Invalidation' }],
    ["ComputeIntersections" /* KnownEventName.ComputeIntersections */, { category: "Paint" /* EventCategory.Paint */, label: 'Compute Intersections' }],
    ["HitTest" /* KnownEventName.HitTest */, { category: "Layout" /* EventCategory.Layout */, label: 'Hit Test' }],
    ["PrePaint" /* KnownEventName.PrePaint */, { category: "Layout" /* EventCategory.Layout */, label: 'Pre-Paint' }],
    /* Paint */
    ["ScrollLayer" /* KnownEventName.ScrollLayer */, { category: "Paint" /* EventCategory.Paint */, label: 'Scroll' }],
    ["UpdateLayer" /* KnownEventName.UpdateLayer */, { category: "Paint" /* EventCategory.Paint */, label: 'Update Layer' }],
    ["PaintSetup" /* KnownEventName.PaintSetup */, { category: "Paint" /* EventCategory.Paint */, label: 'Paint Setup' }],
    ["Paint" /* KnownEventName.Paint */, { category: "Paint" /* EventCategory.Paint */, label: 'Paint' }],
    ["PaintImage" /* KnownEventName.PaintImage */, { category: "Paint" /* EventCategory.Paint */, label: 'Paint Image' }],
    ["Commit" /* KnownEventName.Commit */, { category: "Paint" /* EventCategory.Paint */, label: 'Commit' }],
    ["CompositeLayers" /* KnownEventName.CompositeLayers */, { category: "Paint" /* EventCategory.Paint */, label: 'Composite Layers' }],
    ["RasterTask" /* KnownEventName.RasterTask */, { category: "Paint" /* EventCategory.Paint */, label: 'Raster' }],
    ["ImageDecodeTask" /* KnownEventName.ImageDecodeTask */, { category: "Paint" /* EventCategory.Paint */, label: 'Decode Image Task' }],
    ["ImageUploadTask" /* KnownEventName.ImageUploadTask */, { category: "Paint" /* EventCategory.Paint */, label: 'Upload Image Task' }],
    ["Decode Image" /* KnownEventName.DecodeImage */, { category: "Paint" /* EventCategory.Paint */, label: 'Decode Image' }],
    ["Resize Image" /* KnownEventName.ResizeImage */, { category: "Paint" /* EventCategory.Paint */, label: 'Resize Image' }],
    ["Draw LazyPixelRef" /* KnownEventName.DrawLazyPixelRef */, { category: "Paint" /* EventCategory.Paint */, label: 'Draw LazyPixelRef' }],
    ["Decode LazyPixelRef" /* KnownEventName.DecodeLazyPixelRef */, { category: "Paint" /* EventCategory.Paint */, label: 'Decode LazyPixelRef' }],
    ["GPUTask" /* KnownEventName.GPUTask */, { category: "Paint" /* EventCategory.Paint */, label: 'GPU Task' }],
]);
//# sourceMappingURL=types.js.map