// Copyright 2025 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default {
  cssContent: `/*
 * Copyright (c) 2015 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.widget {
  border-radius: var(--sys-shape-corner-small);
  box-shadow: var(--sys-elevation-level3);
  background: var(--sys-color-cdt-base-container);
  justify-content: flex-start;
  align-items: stretch;
  display: flex;
}

.dialog-close-button {
  position: absolute;
  right: 9px;
  top: 9px;
  z-index: 1;
}

/*# sourceURL=${import.meta.resolve('./dialog.css')} */
`
};