// Copyright 2025 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default {
  cssContent: `/*
 * Copyright 2015 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.tabbed-pane-header-tab {
  & > .tabbed-pane-header-tab-suffix-element devtools-icon.warning {
    width: 14px;
    height: 14px;
    color: var(--icon-warning);
  }
}

/*# sourceURL=${import.meta.resolve('./inspectorViewTabbedPane.css')} */
`
};