// Copyright 2025 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default {
  cssContent: `/*
 * Copyright 2022 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.border-container {
  border-bottom: 1px solid var(--sys-color-divider);
  flex-shrink: 0;
}

.automatic-workspace-infobar {
  border-top: var(--sys-size-1) solid var(--sys-color-divider);
}

/*# sourceURL=${import.meta.resolve('./sourcesNavigator.css')} */
`
};