// Copyright 2021 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2021 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */
.not-restored-reason-list {
  margin: 0;
  list-style-type: none;
  padding-inline-start: 0;
}

.inline-icon {
  vertical-align: sub;
}

/*# sourceURL=backForwardCacheView.css */
`);
export default styles;
