// Copyright 2025 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default {
  cssContent: `/*
 * Copyright (c) 2020 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.data-grid {
  border: none;
}

::part(url-outer) {
  width: 100%;
  display: inline-flex;
  justify-content: flex-start;
}

::part(filter-highlight) {
  font-weight: bold;
}

::part(url-prefix) {
  overflow-x: hidden;
  text-overflow: ellipsis;
}

::part(url-suffix) {
  flex: none;
}

/*# sourceURL=${import.meta.resolve('./developerResourcesListView.css')} */
`
};